import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/shared/providers/theme-provider";
import { TelegramProvider } from "@/shared/providers/telegram-provider";
import Navbar from "@/widgets/navbar/ui/navbar";

// const SFProText = localFont({
//   src: [
//     {
//       path: "../public/fonts/SFProText/SFProText-Regular.ttf",
//       weight: "400",
//       style: "normal",
//     },
//     {
//       path: "../public/fonts/SFProText/SFProText-Medium.ttf",
//       weight: "500",
//       style: "normal",
//     },
//   ],
//   variable: "--font-sf-pro-text",
//   display: "swap",
// });

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin", "cyrillic"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.variable} antialiased h-screen dark`}>
        <TelegramProvider>
          <ThemeProvider
            attribute={"class"}
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <main className="flex flex-col h-screen justify-between">
              {children}
              <Navbar />
            </main>
          </ThemeProvider>
        </TelegramProvider>
      </body>
    </html>
  );
}
